# .bashrc

## ~/.bashrc: executed by bash(1) for non-login shells

umask 002

[ -r $HOME/.bashrc.local ] && source $HOME/.bashrc.local

#
# User specific aliases and functions
#

alias l="ls -lFh"
alias fnf="find . -name .git -prune -o -print"

# Antlr4
alias antlr4='java -jar /usr/local/lib/antlr-4.4-complete.jar'
alias grun='java org.antlr.v4.runtime.misc.TestRig'

alias l="ls -lAF"

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

