# .bashrc

## ~/.bashrc: executed by bash(1) for non-login shells

umask 002

[ -r $HOME/.bashrc.local ] && source $HOME/.bashrc.local

#
# User specific aliases and functions
#

alias l="ls -lFh"

# Clojure
alias leincc="lein clean && lein compile && lein cljsbuild once"
inclj() { find . -name '*.clj' -exec grep -nHr "$1" {} \; ; } 
lsclj() { find . -name .git -prune -o -name '*.clj' -print ; }

# Git
alias lol="git lol -n"
alias gdiff="git diff > diffs.patch"

# Antlr4
if [ -f /usr/local/lib/antlr-4.4-complete.jar ]; then
  alias antlr4='java -jar /usr/local/lib/antlr-4.4-complete.jar'
  alias grun='java org.antlr.v4.runtime.misc.TestRig'
fi

# Emacs 25 (NextStep)
# see URL: http://stuff-things.net/2015/10/13/building-emacs-on-os-x-el-capitan/
if [ -f /Applications/Emacs.app/Contents/MacOS/Emacs ]; then
  alias emacs=/Applications/Emacs.app/Contents/MacOS/Emacs
  alias emacsclient=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient
fi

alias l="ls -lAF"

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

