# Emacs mode
set-option -w -g mode-keys emacs

# set prefix key to C-z
set-option -g prefix C-z        #set -g prefix C-z
unbind-key C-b                  #unbind C-b
bind-key C-z send-prefix        #bind z send-prefix

# tmux attach will create a session if one does not exist
new-session -n $HOME

# Quality of life
set -g default-terminal "screen-256color"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
