

# Added by Toolbox App
export PATH="$PATH:/Users/kmcorbett/Library/Application Support/JetBrains/Toolbox/scripts"


# Setting PATH for Python 3.12
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.12/bin:${PATH}"
export PATH

eval "$(/opt/homebrew/bin/brew shellenv)"
